version: '3.8'

services:
  main-backend:
    build: ./main-backend
    ports:
      - "5000:5000" 
    environment:
      - COMPILER_AI_SERVICE_URL=http://compiler-ai-service:5001 
    env_file: 
      - ./main-backend/.env 
    depends_on:
      - compiler-ai-service 
    volumes:
      - ./main-backend:/app 
      - /app/node_modules 

  compiler-ai-service:
    build: ./compiler-ai-service
    ports:
      - "5001:5001" 
    env_file:
      - ./compiler-ai-service/.env
    volumes:
      - ./compiler-ai-service:/app 
      - /app/node_modules 